"""Subclass of cf_dialogfile, which is generated by wxFormBuilder."""

import wx
import pyhelper_gui_form

# Implementing cf_dialogfile
class pyhelper_cf_dialogfile( pyhelper_gui_form.cf_dialogfile ):
	def __init__( self, parent ):
		pyhelper_gui_form.cf_dialogfile.__init__( self, parent )
		self._configparser = parent._configparser
		self._configfile = self._configparser.config_data
	
	# Handlers for cf_dialogfile events.
	def cf_init( self, event ):
		# TODO: Implement cf_init
		self.m_filePicker1.SetPath( self._configfile['np']['file']['name'] )
	
	def cf_changefile( self, event ):
		# TODO: Implement cf_changefile
		self._configfile['np']['file']['name'] = self.m_filePicker1.GetPath()
	
	def cf_savedata( self, event ):
		# TODO: Implement cf_savedata
		self._configparser.SaveConfig()
		self.Destroy()
	
	
