"""Subclass of cf_dialogpost, which is generated by wxFormBuilder."""

import wx
import gui

# Implementing cf_dialogpost
class pyhelpercf_dialogpost( gui.cf_dialogpost ):
	def __init__( self, parent ):
		gui.cf_dialogpost.__init__( self, parent )
	
	# Handlers for cf_dialogpost events.
	def cf_savedata( self, event ):
		# TODO: Implement cf_savedata
		pass
	
	
