"""Subclass of pyhelper_gui, which is generated by wxFormBuilder."""

import wx
import gui

# Implementing pyhelper_gui
class pyhelperpyhelper_gui( gui.pyhelper_gui ):
	def __init__( self, parent ):
		gui.pyhelper_gui.__init__( self, parent )
	
	# Handlers for pyhelper_gui events.
	def onOutFile( self, event ):
		# TODO: Implement onOutFile
		pass
	
	def onTogglePost( self, event ):
		# TODO: Implement onTogglePost
		pass
	
	def cf_dialogfile( self, event ):
		# TODO: Implement cf_dialogfile
		pass
	
	def cf_dialogpost( self, event ):
		# TODO: Implement cf_dialogpost
		pass
	
	
