"""Subclass of cf_dialogfile, which is generated by wxFormBuilder."""

import wx
import gui

# Implementing cf_dialogfile
class pyhelpercf_dialogfile( gui.cf_dialogfile ):
	def __init__( self, parent ):
		gui.cf_dialogfile.__init__( self, parent )
	
	# Handlers for cf_dialogfile events.
	def cf_changefile( self, event ):
		# TODO: Implement cf_changefile
		pass
	
	def cf_savedata( self, event ):
		# TODO: Implement cf_savedata
		pass
	
	
